(EML) Add exchange monthly limit compliance module
TokenySolutions/T-REX pull request #160
Opened 2023-08-09 10:11 UTC by aliarbak

2023-08-17 08:57 UTC, aliarbak commented
TODO:
- remove onlyComplianceCall modifier from addExchangeID and removeExchangeID functions (need something like onlyOwner for tokeny wallets)

2023-08-17 11:22 UTC, aliarbak commented on test/compliances/module-exchange-monthly-limits.test.ts
> +describe.only('Compliance Module: ExchangeMonthlyLimits', () => {
Remove describe.only

2023-08-17 11:22 UTC, aliarbak commented on test/fixtures/deploy-full-suite.fixture.ts
> +  await compliance.bindToken(context.suite.token.address);
Bind token to the compliance in the test itself (not in the generic fixture file)

2023-08-29 12:29 UTC, Joachim-Lebrun requested changes

2023-08-29 12:29 UTC, Joachim-Lebrun commented on contracts/compliance/modular/modules/ExchangeMonthlyLimitsModule.sol
> +contract ExchangeMonthlyLimitsModule is AbstractModule {
```suggestion
import "@openzeppelin/contracts/access/Ownable.sol";

contract ExchangeMonthlyLimitsModule is AbstractModule, Ownable {
```

2023-08-29 12:29 UTC, Joachim-Lebrun commented on contracts/compliance/modular/modules/ExchangeMonthlyLimitsModule.sol
> +    mapping(address => mapping(address => bool)) private _exchangeIDs;
```suggestion
    mapping(address => bool) private _exchangeIDs;
```

2023-08-29 12:29 UTC, Joachim-Lebrun commented on contracts/compliance/modular/modules/ExchangeMonthlyLimitsModule.sol
> +    event ExchangeIDAdded(address indexed compliance, address _newExchangeID);
```suggestion
    event ExchangeIDAdded(address indexed _newExchangeID);
```

2023-08-29 12:29 UTC, Joachim-Lebrun commented on contracts/compliance/modular/modules/ExchangeMonthlyLimitsModule.sol
> +    event ExchangeIDRemoved(address indexed compliance, address _exchangeID);
```suggestion
    event ExchangeIDRemoved(address indexed _exchangeID);
```

2023-08-29 12:29 UTC, Joachim-Lebrun commented on contracts/compliance/modular/modules/ExchangeMonthlyLimitsModule.sol
> +    error ONCHAINIDAlreadyTaggedAsExchange(address compliance, address _exchangeID);
```suggestion
    error ONCHAINIDAlreadyTaggedAsExchange(address _exchangeID);
```

2023-08-29 12:29 UTC, Joachim-Lebrun commented on contracts/compliance/modular/modules/ExchangeMonthlyLimitsModule.sol
> +    error ONCHAINIDNotTaggedAsExchange(address compliance, address _exchangeID);
```suggestion
    error ONCHAINIDNotTaggedAsExchange(address _exchangeID);
```

2023-08-29 12:29 UTC, Joachim-Lebrun commented on contracts/compliance/modular/modules/ExchangeMonthlyLimitsModule.sol
> +    function addExchangeID(address _exchangeID) external onlyComplianceCall {
```suggestion
    function addExchangeID(address _exchangeID) external onlyOwner {
```

2023-08-29 12:29 UTC, Joachim-Lebrun commented on contracts/compliance/modular/modules/ExchangeMonthlyLimitsModule.sol
> +            revert ONCHAINIDAlreadyTaggedAsExchange(msg.sender, _exchangeID);
```suggestion
            revert ONCHAINIDAlreadyTaggedAsExchange(_exchangeID);
```

2023-08-29 12:29 UTC, Joachim-Lebrun commented on contracts/compliance/modular/modules/ExchangeMonthlyLimitsModule.sol
> +        _exchangeIDs[msg.sender][_exchangeID] = true;
```suggestion
        _exchangeIDs[_exchangeID] = true;
```

2023-08-29 12:29 UTC, Joachim-Lebrun commented on contracts/compliance/modular/modules/ExchangeMonthlyLimitsModule.sol
> +        emit ExchangeIDAdded(msg.sender, _exchangeID);
```suggestion
        emit ExchangeIDAdded(_exchangeID);
```

2023-08-29 12:29 UTC, Joachim-Lebrun commented on contracts/compliance/modular/modules/ExchangeMonthlyLimitsModule.sol
> +    *  Function can be called only by the compliance contract
```suggestion
    *  Function can be called only by the owner of this module
```

2023-08-29 12:29 UTC, Joachim-Lebrun commented on contracts/compliance/modular/modules/ExchangeMonthlyLimitsModule.sol
> +    *  Function can be called only by the compliance contract
```suggestion
    *  Function can be called only by the Owner of this module
```

2023-08-29 12:29 UTC, Joachim-Lebrun commented on contracts/compliance/modular/modules/ExchangeMonthlyLimitsModule.sol
> +    function removeExchangeID(address _exchangeID) external onlyComplianceCall {
```suggestion
    function removeExchangeID(address _exchangeID) external onlyOwner {
```

2023-08-29 12:29 UTC, Joachim-Lebrun commented on contracts/compliance/modular/modules/ExchangeMonthlyLimitsModule.sol
> +        if (!isExchangeID(msg.sender, _exchangeID)) {
```suggestion
        if (!isExchangeID(_exchangeID)) {
```

2023-08-29 12:29 UTC, Joachim-Lebrun commented on contracts/compliance/modular/modules/ExchangeMonthlyLimitsModule.sol
> +            revert ONCHAINIDNotTaggedAsExchange(msg.sender, _exchangeID);
```suggestion
            revert ONCHAINIDNotTaggedAsExchange(_exchangeID);
```

2023-08-29 12:29 UTC, Joachim-Lebrun commented on contracts/compliance/modular/modules/ExchangeMonthlyLimitsModule.sol
> +        _exchangeIDs[msg.sender][_exchangeID] = false;
```suggestion
        delete _exchangeIDs[_exchangeID];
```

2023-08-29 12:29 UTC, Joachim-Lebrun commented on contracts/compliance/modular/modules/ExchangeMonthlyLimitsModule.sol
> +        emit ExchangeIDRemoved(msg.sender, _exchangeID);
```suggestion
        emit ExchangeIDRemoved(_exchangeID);
```

2023-08-29 12:29 UTC, Joachim-Lebrun commented on contracts/compliance/modular/modules/ExchangeMonthlyLimitsModule.sol
> +    *  @param compliance the Compliance smart contract to be checked
```suggestion
    
```

2023-08-29 12:29 UTC, Joachim-Lebrun commented on contracts/compliance/modular/modules/ExchangeMonthlyLimitsModule.sol
> +    function isExchangeID(address compliance, address _exchangeID) public view returns (bool){
```suggestion
    function isExchangeID(address _exchangeID) public view returns (bool){
```

2023-08-29 12:29 UTC, Joachim-Lebrun commented on contracts/compliance/modular/modules/ExchangeMonthlyLimitsModule.sol
> +        return _exchangeIDs[compliance][_exchangeID];
```suggestion
        return _exchangeIDs[_exchangeID];
```

2023-09-14 09:13 UTC, Joachim-Lebrun approved these changes

2023-09-14 09:13 UTC, merged