(TFM) Add transfer fees module
TokenySolutions/T-REX pull request #168
Opened 2023-09-20 11:05 UTC by aliarbak

Notes:
- The minimum fee rate is 0.01% but must be given in uint format. So, when defining fee rates:
  - 1 = 0.01%
  - 10 = 0.1%
  - 100 = 1%
  - 1000 = 10%
  - 10000 = 100%
- `canComplianceBind` function is for the plug-and-play support discussed before. It checks whether the module is a token agent (and is required for it to work). It should be called from the `addComplianceModule`
-- This is a draft function, I can update it after we decide how to proceed with the plug-and-play support.

2023-10-02 11:59 UTC, Joachim-Lebrun commented on contracts/compliance/modular/modules/TransferFeesModule.sol
> +    function setFee(address _compliance, uint256 _rate, address _collector) external {
all owner scoped functions should be called through the ModularCompliance function `callModuleFunction` in order to standardize the way we setup modules. some exceptions can exist, if for some reason it is not possible to achieve the desired behaviour this way, but when possible it is better to do it. Please update the function to be called by the modular compliance through `callModuleFunction`

2023-10-02 12:02 UTC, Joachim-Lebrun commented on contracts/compliance/modular/modules/TransferFeesModule.sol
> +        if (_collector == address(0)) {
if the address is zero address `isVerified` that is called right after will return `false` therefore we can remove this check here

2023-10-02 12:07 UTC, Joachim-Lebrun commented on contracts/compliance/modular/modules/TransferFeesModule.sol
> +            return;
i believe this part is unreachable as the token contract will never call the `transferred` function with zero address as `_from` or `_to`, we can remove this check imo

2023-10-02 12:16 UTC, Joachim-Lebrun requested changes
- add the `isPlugAndPlay` and `canComplianceBind` after #169 is merged to develop
- remove useless checks to save gas
- modify `setFee` function to be called by the Modular Compliance contract

2023-10-03 08:07 UTC, Joachim-Lebrun commented
just need to still add the `isPlugAndPlay` and `canComplianceBind` functions, which are both always returning `true`

2023-10-05 08:53 UTC, aliarbak commented
Hey @Joachim-Lebrun, I need to rebase from develop, can you allow me to force-push to the transfer-fees-module branch?

2023-10-06 11:51 UTC, Joachim-Lebrun approved these changes

2023-10-06 11:51 UTC, merged