TREX-14 Eligibility & Compliance checker contract
TokenySolutions/T-REX pull request #218
Opened 2024-08-05 07:32 UTC by pgonday

2024-08-09 07:42 UTC, Nakasar commented on package.json
> +    "hardhat-tracer": "^3.0.3"
Should be in `devDependencies`

```bash
npm uninstall hardhat-tracer && npm install --save-dev hardhat-tracer
```

2024-08-21 03:52 UTC, Joachim-Lebrun commented on contracts/utilities/IUtilityChecker.sol
> +    function testTransfer(address _compliance, address _token, address _from, address _to, uint256 _amount)
the interface can be simplified by removing the compliance address, this address can be found easily if you have the token address as there is a getter on the token interface to get the compliance address.

2024-10-16 10:43 UTC, Joachim-Lebrun commented
@pgonday can you solve the conflicts on the PR please ?

2024-10-16 11:21 UTC, Joachim-Lebrun requested changes

2024-10-16 11:21 UTC, Joachim-Lebrun commented on contracts/utilities/UtilityChecker.sol
> +        external view override returns (bool) {
we could make this function return 3 boolean values 
```suggestion
        external view override returns (bool _freezeStatus, bool _eligibilityStatus, bool _complianceStatus) {
```
This way the user knows immediately where to check to get the explanation of why the transfer is going to fail

2024-10-16 11:21 UTC, Joachim-Lebrun commented on contracts/utilities/UtilityChecker.sol
> +        ComplianceCheckDetails [] memory details = testTransferDetails(_token, _from, _to, _amount);
you check compliance, pause and freeze but not the eligibility in this function, which means that right now a transfer that would block at the eligibility level will return true, while it should return false. You need to check the eligibility on the receiver address (just need to call `isVerified` on the IR of the token

2024-10-16 11:21 UTC, Joachim-Lebrun commented on contracts/utilities/UtilityChecker.sol
> +        ComplianceCheckDetails [] memory details = testTransferDetails(_token, _from, _to, _amount);
```suggestion
        IIdentityRegistry ir = token.identityRegistry();
        if(!ir.isVerified(_to)) return false; 
        ComplianceCheckDetails [] memory details = testTransferDetails(_token, _from, _to, _amount);
```

2024-10-18 08:58 UTC, pgonday commented
Relaced by https://github.com/TokenySolutions/T-REX/pull/229

2024-10-18 08:58 UTC, closed without merging